//LOS HANDLERS VAN A SER LOS ENCARGADOS DE RECIBIR LAS PETICIONES Y RESPONDERLAS
//ADEMAS DE INTERACTUAR CON LA BASE DE DATOS SI ES NECESARIO
//ES DECIR, TODAS LAS FUNCIONES DE LOS MODELOS SE VAN A MANEJAR DESDE AQUI

package handlers

import (
	"fmt"
)

func main() {
	fmt.Printf("HANDLER EJEMPLO")
}