//DE MOMENTO NO HAY NADA EN ESTE ARCHIVO, DEJENME EXPLICAR EL PORQUE...
//EL LENGUAJE "GO" ES UN LENGUAJE 100% DEDICADO AL BACKEND Y ES CON EL QUE VAMOS A TRABAJAR
//QUE PASA? PUES QUE LEYENDO LA PLANIFICACION DEL PROYECTO HAY
//VARIAS COSAS LAS CUALES DEBO DE PLANEAR ANTES DE PODER EMPEZAR A PROGRAMAR
//1. LA BASE DE DATOS VA A SER POSTGRESQL PERO COMO SE VA A ESTRUCTURAR?
//2. COMO SE VA A ESTRUCTURAR LA CARPETA BACKEND?
//3. SE NOS PIDIO BUSCAR UNA EMPRESA REAL (EN ESTE CASO UNA PRODUCTORA DE AUDITORIA) PARA ASI
//   PODER CONTACTARLOS Y PEDIRLES QUE NOS DEN UNA IDEA DE COMO ELLOS HACEN LAS COSAS
//   PARA ASI PODER IMPLEMENTARLO EN NUESTRO PROYECTO

//DE MOMENTO ESTO SE QUEDARA ASI, ASI QUE SE VA A IR TRABAJANDO EN LA INTERFAZ.

package main

import "fmt"

func main() {
	fmt.Printf("HOLA MUNDO")
}