//ESTE VA A SER EL ARCHIVO DONDE VAMOS A DEFINIR LOS MODELOS DE LA BASE DE DATOS
//ES DECIR, LAS ESTRUCTURAS DE LOS OBJETOS QUE VAMOS A UTILIZAR
//PARA QUE EL ORM (OBJECT RELATIONAL MAPPER) GESTIONE LA BASE DE DATOS

package models

import (
)